[2025-03-17T20:30:42.093+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T20:30:42.283+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.load_analytics_sessions scheduled__2025-03-17T20:20:00+00:00 [queued]>
[2025-03-17T20:30:42.402+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.load_analytics_sessions scheduled__2025-03-17T20:20:00+00:00 [queued]>
[2025-03-17T20:30:42.412+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-17T20:30:42.593+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): load_analytics_sessions> on 2025-03-17 20:20:00+00:00
[2025-03-17T20:30:42.644+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3707) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-17T20:30:42.663+0000] {standard_task_runner.py:72} INFO - Started process 3708 to run task
[2025-03-17T20:30:42.663+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'load_analytics_sessions', 'scheduled__2025-03-17T20:20:00+00:00', '--job-id', '266', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp1i7es8a3']
[2025-03-17T20:30:42.673+0000] {standard_task_runner.py:105} INFO - Job 266: Subtask load_analytics_sessions
[2025-03-17T20:30:43.143+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.load_analytics_sessions scheduled__2025-03-17T20:20:00+00:00 [running]> on host c032966e105e
[2025-03-17T20:30:44.223+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='load_analytics_sessions' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T20:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-17T20:20:00+00:00'
[2025-03-17T20:30:44.253+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-17T20:30:44.463+0000] {sql.py:278} INFO - Executing: select load_analytics_sessions();
[2025-03-17T20:30:44.592+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T20:30:44.742+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T20:30:44.793+0000] {sql.py:553} INFO - Running statement: select load_analytics_sessions();, parameters: None
[2025-03-17T20:30:45.283+0000] {sql.py:562} INFO - Rows affected: 1
[2025-03-17T20:30:46.142+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-17T20:30:46.154+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=load_analytics_sessions, run_id=scheduled__2025-03-17T20:20:00+00:00, execution_date=20250317T202000, start_date=20250317T203042, end_date=20250317T203046
[2025-03-17T20:30:46.473+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T20:30:46.790+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-17T20:30:46.860+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
