[2025-03-17T20:40:29.961+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T20:40:32.421+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.load_tables.user_sessions_project_b_db scheduled__2025-03-17T20:30:00+00:00 [queued]>
[2025-03-17T20:40:33.240+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.load_tables.user_sessions_project_b_db scheduled__2025-03-17T20:30:00+00:00 [queued]>
[2025-03-17T20:40:33.251+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-17T20:40:35.080+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): load_tables.user_sessions_project_b_db> on 2025-03-17 20:30:00+00:00
[2025-03-17T20:40:36.161+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3816) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-17T20:40:36.250+0000] {standard_task_runner.py:72} INFO - Started process 3834 to run task
[2025-03-17T20:40:36.441+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'load_tables.user_sessions_project_b_db', 'scheduled__2025-03-17T20:30:00+00:00', '--job-id', '272', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp96gj8w63']
[2025-03-17T20:40:36.900+0000] {standard_task_runner.py:105} INFO - Job 272: Subtask load_tables.user_sessions_project_b_db
[2025-03-17T20:40:41.830+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.load_tables.user_sessions_project_b_db scheduled__2025-03-17T20:30:00+00:00 [running]> on host c032966e105e
[2025-03-17T20:40:43.951+0000] {job.py:229} INFO - Heartbeat recovered after 16.83 seconds
