[2025-03-17T20:30:19.363+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T20:30:19.913+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.load_tables.events_project_a_db scheduled__2025-03-17T20:20:00+00:00 [queued]>
[2025-03-17T20:30:20.303+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.load_tables.events_project_a_db scheduled__2025-03-17T20:20:00+00:00 [queued]>
[2025-03-17T20:30:20.392+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-17T20:30:21.982+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): load_tables.events_project_a_db> on 2025-03-17 20:20:00+00:00
[2025-03-17T20:30:22.813+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3680) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-17T20:30:22.824+0000] {standard_task_runner.py:72} INFO - Started process 3698 to run task
[2025-03-17T20:30:23.062+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'load_tables.events_project_a_db', 'scheduled__2025-03-17T20:20:00+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpm0dt9jmg']
[2025-03-17T20:30:23.153+0000] {standard_task_runner.py:105} INFO - Job 263: Subtask load_tables.events_project_a_db
[2025-03-17T20:30:24.554+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.load_tables.events_project_a_db scheduled__2025-03-17T20:20:00+00:00 [running]> on host c032966e105e
[2025-03-17T20:30:29.062+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='load_tables.events_project_a_db' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T20:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-17T20:20:00+00:00'
[2025-03-17T20:30:29.083+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-17T20:30:29.252+0000] {job.py:229} INFO - Heartbeat recovered after 11.31 seconds
[2025-03-17T20:30:29.973+0000] {sql.py:278} INFO - Executing: select load_tables('events_project_a_db', 'events');
[2025-03-17T20:30:30.443+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T20:30:31.233+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T20:30:31.423+0000] {sql.py:553} INFO - Running statement: select load_tables('events_project_a_db', 'events');, parameters: None
[2025-03-17T20:30:31.763+0000] {sql.py:562} INFO - Rows affected: 1
[2025-03-17T20:30:32.763+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-17T20:30:32.812+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=load_tables.events_project_a_db, run_id=scheduled__2025-03-17T20:20:00+00:00, execution_date=20250317T202000, start_date=20250317T203019, end_date=20250317T203032
[2025-03-17T20:30:33.353+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T20:30:33.442+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-03-17T20:30:34.043+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
