[2025-03-17T20:30:19.193+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T20:30:19.523+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.load_tables.user_sessions_project_c_db scheduled__2025-03-17T20:20:00+00:00 [queued]>
[2025-03-17T20:30:19.712+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.load_tables.user_sessions_project_c_db scheduled__2025-03-17T20:20:00+00:00 [queued]>
[2025-03-17T20:30:19.732+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-17T20:30:20.842+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): load_tables.user_sessions_project_c_db> on 2025-03-17 20:20:00+00:00
[2025-03-17T20:30:21.833+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'load_tables.user_sessions_project_c_db', 'scheduled__2025-03-17T20:20:00+00:00', '--job-id', '262', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp4ionzlyg']
[2025-03-17T20:30:21.803+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3675) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-17T20:30:21.863+0000] {standard_task_runner.py:105} INFO - Job 262: Subtask load_tables.user_sessions_project_c_db
[2025-03-17T20:30:21.864+0000] {standard_task_runner.py:72} INFO - Started process 3694 to run task
[2025-03-17T20:30:24.723+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.load_tables.user_sessions_project_c_db scheduled__2025-03-17T20:20:00+00:00 [running]> on host c032966e105e
[2025-03-17T20:30:28.663+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='load_tables.user_sessions_project_c_db' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T20:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-17T20:20:00+00:00'
[2025-03-17T20:30:28.713+0000] {job.py:229} INFO - Heartbeat recovered after 11.03 seconds
[2025-03-17T20:30:28.793+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-17T20:30:29.314+0000] {sql.py:278} INFO - Executing: select load_tables('user_sessions_project_c_db', 'user_sessions');
[2025-03-17T20:30:30.123+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T20:30:30.743+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T20:30:31.182+0000] {sql.py:553} INFO - Running statement: select load_tables('user_sessions_project_c_db', 'user_sessions');, parameters: None
[2025-03-17T20:30:31.462+0000] {sql.py:562} INFO - Rows affected: 1
[2025-03-17T20:30:32.403+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-17T20:30:32.412+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=load_tables.user_sessions_project_c_db, run_id=scheduled__2025-03-17T20:20:00+00:00, execution_date=20250317T202000, start_date=20250317T203019, end_date=20250317T203032
[2025-03-17T20:30:33.093+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T20:30:33.263+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-03-17T20:30:34.093+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-17T20:30:34.182+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
