[2025-03-17T20:20:34.731+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T20:20:34.950+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.load_analytics_sessions scheduled__2025-03-17T20:10:00+00:00 [queued]>
[2025-03-17T20:20:35.031+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.load_analytics_sessions scheduled__2025-03-17T20:10:00+00:00 [queued]>
[2025-03-17T20:20:35.049+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-17T20:20:35.230+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): load_analytics_sessions> on 2025-03-17 20:10:00+00:00
[2025-03-17T20:20:35.291+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3567) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-17T20:20:35.311+0000] {standard_task_runner.py:72} INFO - Started process 3568 to run task
[2025-03-17T20:20:35.320+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'load_analytics_sessions', 'scheduled__2025-03-17T20:10:00+00:00', '--job-id', '256', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpzxzasg8r']
[2025-03-17T20:20:35.339+0000] {standard_task_runner.py:105} INFO - Job 256: Subtask load_analytics_sessions
[2025-03-17T20:20:35.900+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.load_analytics_sessions scheduled__2025-03-17T20:10:00+00:00 [running]> on host c032966e105e
[2025-03-17T20:20:37.050+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='load_analytics_sessions' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T20:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-17T20:10:00+00:00'
[2025-03-17T20:20:37.060+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-17T20:20:37.210+0000] {sql.py:278} INFO - Executing: select load_analytics_sessions();
[2025-03-17T20:20:37.300+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T20:20:37.380+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T20:20:37.440+0000] {sql.py:553} INFO - Running statement: select load_analytics_sessions();, parameters: None
[2025-03-17T20:20:37.571+0000] {sql.py:562} INFO - Rows affected: 1
[2025-03-17T20:20:37.840+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-17T20:20:37.850+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=load_analytics_sessions, run_id=scheduled__2025-03-17T20:10:00+00:00, execution_date=20250317T201000, start_date=20250317T202034, end_date=20250317T202037
[2025-03-17T20:20:38.109+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T20:20:38.301+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-17T20:20:38.329+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
