[2025-03-17T19:01:35.962+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T19:01:36.131+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.load_tables.events_project_c_db scheduled__2025-03-17T18:00:00+00:00 [queued]>
[2025-03-17T19:01:36.199+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.load_tables.events_project_c_db scheduled__2025-03-17T18:00:00+00:00 [queued]>
[2025-03-17T19:01:36.210+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-17T19:01:36.489+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): load_tables.events_project_c_db> on 2025-03-17 18:00:00+00:00
[2025-03-17T19:01:36.552+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2425) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-17T19:01:36.581+0000] {standard_task_runner.py:72} INFO - Started process 2445 to run task
[2025-03-17T19:01:36.610+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'load_tables.events_project_c_db', 'scheduled__2025-03-17T18:00:00+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpcf3h8gfa']
[2025-03-17T19:01:36.620+0000] {standard_task_runner.py:105} INFO - Job 156: Subtask load_tables.events_project_c_db
[2025-03-17T19:01:37.362+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.load_tables.events_project_c_db scheduled__2025-03-17T18:00:00+00:00 [running]> on host c032966e105e
[2025-03-17T19:01:38.562+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='load_tables.events_project_c_db' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-17T18:00:00+00:00'
[2025-03-17T19:01:38.599+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-17T19:01:38.870+0000] {sql.py:278} INFO - Executing: select load_tables('events_project_c_db', 'events');
[2025-03-17T19:01:38.978+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T19:01:39.089+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T19:01:39.112+0000] {sql.py:553} INFO - Running statement: select load_tables('events_project_c_db', 'events');, parameters: None
[2025-03-17T19:01:41.078+0000] {sql.py:562} INFO - Rows affected: 1
[2025-03-17T19:01:41.410+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-17T19:01:41.411+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=load_tables.events_project_c_db, run_id=scheduled__2025-03-17T18:00:00+00:00, execution_date=20250317T180000, start_date=20250317T190136, end_date=20250317T190141
[2025-03-17T19:01:41.578+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T19:01:41.629+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-03-17T19:01:41.661+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
