[2025-03-17T20:01:08.033+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T20:01:08.311+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.load_analytics_sessions scheduled__2025-03-17T19:50:00+00:00 [queued]>
[2025-03-17T20:01:08.433+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.load_analytics_sessions scheduled__2025-03-17T19:50:00+00:00 [queued]>
[2025-03-17T20:01:08.441+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-17T20:01:08.592+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): load_analytics_sessions> on 2025-03-17 19:50:00+00:00
[2025-03-17T20:01:08.661+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3296) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-17T20:01:08.673+0000] {standard_task_runner.py:72} INFO - Started process 3297 to run task
[2025-03-17T20:01:08.682+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'load_analytics_sessions', 'scheduled__2025-03-17T19:50:00+00:00', '--job-id', '235', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpk65hbba1']
[2025-03-17T20:01:08.692+0000] {standard_task_runner.py:105} INFO - Job 235: Subtask load_analytics_sessions
[2025-03-17T20:01:09.472+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.load_analytics_sessions scheduled__2025-03-17T19:50:00+00:00 [running]> on host c032966e105e
[2025-03-17T20:01:10.691+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='load_analytics_sessions' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T19:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-17T19:50:00+00:00'
[2025-03-17T20:01:10.692+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-17T20:01:11.152+0000] {sql.py:278} INFO - Executing: select load_analytics_sessions();
[2025-03-17T20:01:11.252+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T20:01:11.353+0000] {base.py:84} INFO - Retrieving connection 'con_agg'
[2025-03-17T20:01:11.422+0000] {sql.py:553} INFO - Running statement: select load_analytics_sessions();, parameters: None
[2025-03-17T20:01:11.911+0000] {sql.py:562} INFO - Rows affected: 1
[2025-03-17T20:01:12.612+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-17T20:01:12.622+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=load_analytics_sessions, run_id=scheduled__2025-03-17T19:50:00+00:00, execution_date=20250317T195000, start_date=20250317T200108, end_date=20250317T200112
[2025-03-17T20:01:13.051+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T20:01:13.291+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-17T20:01:13.373+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-17T20:01:13.712+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
